###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=dev_appota_ewallet_insurance
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
        - "3331:3306"

    webserver:
      build: setup_local/phpdocker/nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./setup_local/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          # - ./phpdocker/nginx/certs:/etc/nginx/certs
      ports:
       - "110:80"
      #  - "443:443"
      links:
        - mysql
        - mailcatcher
      environment:
        - PMA_HOST=mysql
        - UPLOAD_LIMIT=300M

    php-fpm:
      build: setup_local/phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./setup_local/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
        #- ./phpdocker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      links:
        - mysql
        - mailcatcher
      environment:
        - PMA_HOST=mysql
        - UPLOAD_LIMIT=300M

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      working_dir: /application
      ports:
       - "8107:80"
      links:
       - mysql
      environment:
        - PMA_HOST=mysql
        - UPLOAD_LIMIT=300M
    
    redis:
      image: 'bitnami/redis:latest'
      command: ["redis-server", "/etc/redis/redis.conf"]
      platform: linux/amd64
      environment:
        - REDIS_DATABASE=0
        - REDIS_PASSWORD=12345678
        - REDIS_TLS_ENABLED=yes
        - REDIS_TLS_PORT_NUMBER=6379
        - REDIS_TLS_CERT_FILE=/etc/redis/redis.crt
        - REDIS_TLS_KEY_FILE=/etc/redis/redis.key
        - REDIS_TLS_CA_FILE=/etc/redis/ca.crt
      volumes:
        - ./setup_local/conf/redis_local.conf:/etc/redis/redis.conf
        - ./setup_local/certs/redis/redis.crt:/etc/redis/redis.crt
        - ./setup_local/certs/redis/redis.key:/etc/redis/redis.key
        - ./setup_local/certs/redis/ca.crt:/etc/redis/ca.crt

    mailcatcher:
      image: schickling/mailcatcher
      ports:
       - "1105:1080"
       - "1044:1025"
